[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codes"
version = "0.1.0"
description = "Utility classes and methods that I use across projects in my PhD, on using high-res geodetic data and probabilistic inversions to probe the damage zone around faults."
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "arviz>=0.16.0",
    "cmcrameri>=1.9",
    "geopandas>=1.0.1",
    # Add runtime dependencies here
    "matplotlib>=3.9.4",
    "numba>=0.60.0",
    "numpy>=2.0.2",
    "pymc>=5.12.0",
    "pyproj>=3.6.1",
    "rioxarray>=0.15.0",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "shapely>=2.0.7",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
]
